### ISSUE TITLE
Preliminary UKBB based maps?

### ISSUE THREAD

**Issue by JosephLalli** [ZhiGroup/FastRecomb#1]
Are they available to the public?

**Comment by ardalan-n** [comment]
Hi,

**The map from UK Biobank has not been made public yet**. We demonstrated the result for one chromosome in our paper. But if you have access to the UK Biobank, you can run the code using the phased haplotypes, and it would take a few hours on average per chromosome. We plan to provide population-specific maps in the future using UK Biobank (and other data sets), but we cannot provide a specific timeline at this moment.

Best,
Ardalan

**Comment by JosephLalli** [comment]
Out of curiosity, I see population based maps being made much more frequently than global maps. Is that because global maps are a solved problem? (For GRCh37/38, at least?) Or are there more fundamental issues with using global recombination maps?

(And will your map always be behind the UK Biobank paywall?)

**Comment by ardalan-n** [comment]
The increasing availability of data from various populations is driving the consideration of population-specific genetic maps, as global or universal maps may not accurately represent all populations at a fine scale. 
While there are some concerns about privacy regarding the UK Biobank, it is unlikely that the genetic map would violate any privacy regulations. Nevertheless, we will seek permission, and I hope it will not remain behind the UK Biobank paywall.

**Comment by JosephLalli** [comment]
Thanks for your helpful answers @ardalan-n. Good luck, and I look forward to using the resources your efforts produce!

Best,
Joe
