### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by dosshra** [ZhiGroup/FastRecomb#2]
Hi
I run the command as described in  README. I use either the example file or my own file.  
`./FastRecomb  -i sample_panel_1.vcf  -L 100 -o ./ `
 I get theses messages: 

> total matches: 19
> total matches: 91
>total matches: 130
>total matches: 168
>total matches: 166

but no output file. Thank you

**Comment by ardalan-n** [comment]
Hi, you need to provide a prefix for the output file(s):

./FastRecomb -i sample_panel_1.vcf  -L 100 -o ./test_output

-rw-r--r-- 1 9.3K Jan 29 11:21 test_output.map
-rw-r--r-- 1  15K Jan 29 11:21 test_output.pbwt
-rw-r--r-- 1 1.8K Jan 29 11:21 test_output.raw

Best,
Ardalan
