### ISSUE TITLE
whether the FastRecomb software can output thecrossovers per individual

### ISSUE THREAD

**Issue by ChinJCheung** [ZhiGroup/FastRecomb#3]
Hi, I am very interested in whether the FastRecomb software can output the number of recombinations (crossovers) per individual. Can this software generate such a result? Or if a reference individual is specified, can it calculate the crossovers that have occurred in each individual?

**Comment by ardalan-n** [comment]
Hi! Currently, the program only generates the genetic map from a population cohort. I will try incorporating this feature in the next release but I cannot give any timeline.

**Comment by ChinJCheung** [comment]
I eagerly anticipate the release of your next version.
